# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./:/var/www/html
#     environment:
#       - APP_NAME=MyApp
#       - APP_ENV=production
#       - APP_KEY=
#       - APP_DEBUG=false
#       - APP_URL=https://myapp.railway.app
#       - LOG_CHANNEL=stderr
#     command: php-fpm
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       - MYSQL_DATABASE=myapp
#       - MYSQL_USER=myuser
#       - MYSQL_PASSWORD=mypassword
#       - MYSQL_ROOT_PASSWORD=myrootpassword
#     ports:
#       - '3306:3306'
#     volumes:
#       - ./mysql-data:/var/lib/mysql

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=containers-us-west-150.railway.app"
      - "DB_PORT=7817"
      - "DB_DATABASE=railway"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=KfckI33MOw4GsaglSeq9"

